FROM debian:stable-slim
RUN apt update
RUN apt install -y python3
RUN apt install -y g++
RUN apt install -y mono-devel
RUN apt install -y golang
RUN apt install -y ruby-full
RUN apt install -y php
RUN apt install -y nodejs
RUN apt install -y default-jdk
